# Dosya Konumu: pubspec.yaml

name: linkcim
description: Süper Güçlü Video İndirme ve Akıllı AI Analiz Uygulaması - Her türlü videoyu indir, kategorize et ve organize et!
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Veritabanı - Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # HTTP istekleri ve API - Gelişmiş
  http: ^1.2.1
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3

  # Link açma ve URL yönetimi
  url_launcher: ^6.2.5

  # Tarih ve zaman formatlama
  intl: ^0.19.0

  # UI ikonları ve tasarım
  cupertino_icons: ^1.0.6

  # Video ve Web özellikleri
  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.0.0

  # Paylaşma ve clipboard
  share_plus: ^9.0.0

  # Dosya açma - Gelişmiş
  open_file: ^3.5.4

  # Galeri kayıt
  gal: ^2.3.0

  # Görsel önbellekleme ve resim yönetimi
  cached_network_image: ^3.3.1

  # JSON serialization
  json_annotation: ^4.9.0

  # Dosya yönetimi ve storage
  shared_preferences: ^2.2.3

  # State yönetimi
  provider: ^6.1.2

  # Permission handling - Gelişmiş
  permission_handler: ^12.0.0+1

  # Device info
  device_info_plus: ^10.1.0

  # Package info
  package_info_plus: ^8.0.0

  # UUID generator
  uuid: ^4.4.0

  # Video ve Audio işleme - Güncel ve uyumlu paketler
  video_player: ^2.8.6
  chewie: ^1.8.1
  
  # Dosya seçme ve işleme - Gelişmiş
  file_picker: ^8.0.0+1
  image_picker: ^1.1.2
  
  # Video thumbnail oluşturma - Güçlendirilmiş
  video_thumbnail: ^0.5.3
  
  # Audio kayıt ve çalma - İsteğe bağlı
  record: ^5.1.0
  just_audio: ^0.9.39
  
  # Audio waveforms - İsteğe bağlı
  audio_waveforms: ^1.0.5

  # Network ve download optimizasyonu (opsiyonel)
  # dio_cache_interceptor: ^3.5.0
  # dio_certificate_pinning: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation - Hive için
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

  # Linting and analysis
  flutter_lints: ^4.0.0

  # Testing utilities
  mockito: ^5.4.4

  # Integration testing
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # App assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/data/

  # Custom fonts - Premium görünüm için (şimdilik devre dışı)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700

# Analyzer ayarları - Gelişmiş
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: info

# Linter kuralları - Production ready
linter:
  rules:
    # Dart style guide
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - avoid_empty_else
    - avoid_print
    - avoid_returning_null_for_void
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - close_sinks
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - use_key_in_widget_constructors
    
    # Performance
    - avoid_unnecessary_containers
    - prefer_collection_literals
    - prefer_spread_collections
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    
    # Safety
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - empty_catches
    - hash_and_equals
    - no_duplicate_case_values
    - valid_regexps


